evaluation/evaluation_engine.py

Some changes to the code as I try to create the leaderboard:
1. change the arg name `model` to `model_name` in `evaluation_engine` to make it consistent with others. It also fixes the bug in the colab
2. add returns to all the eval function.
3. add a simple input key arg to text classification. Also added exception to this function when cannot find the data entry. 
TODO: should extend text classification beyond just sentiment analysis; And should expose the instance keyword and label keywords to let people build the mapping (rather than pre-specify as pos/neg/1/0)

Some refactoring on evaluation engine.

---

TestRunner.py
test/test_main.py

- adding light/all/name option for testing filters
- renaming test_transformation to test_oepration

adding light/all/name option for testing filters

---

.github/workflows/nl-action.yml
README.md
TestRunner.py
docs/doc.md
filters/keywords/README.md
filters/length/README.md
test/test_main.py
transformations/back_translation/__init__.py
transformations/back_translation/test.json
transformations/butter_fingers_perturbation/__init__.py
transformations/butter_fingers_perturbation/test.json
transformations/butter_fingers_perturbation/transformation.py
transformations/change_person_named_entities/__init__.py
transformations/change_person_named_entities/test.json
transformations/change_two_way_ne/__init__.py
transformations/change_two_way_ne/test.json
transformations/change_two_way_ne/transformation.py
transformations/longer_names_ner/__init__.py
transformations/longer_names_ner/test.json
transformations/longer_names_ner/transformation.py
transformations/punctuation/__init__.py
transformations/punctuation/test.json
transformations/redundant_context_for_qa/__init__.py
transformations/redundant_context_for_qa/test.json
transformations/redundant_context_for_qa/transformation.py
transformations/replace_numerical_values/__init__.py
transformations/replace_numerical_values/test.json

+ Ability to write multiple transformations and test cases in a single file
+ Merged common implementations of filters and transformations.
+ README updates
+ Make test case writing non-mandatory but encouraged.

Transformation folders can now support multiple implementations in a single transformations.py file

---

README.md
docs/doc.md

3 implementations would be selected as the most creative ones.

Update README.md for creativity selection

---

.github/workflows/nl-action.yml

Fixed GitHub action plan

---

docs/doc.md

Your contribution should be different from earlier submissions

Your contribution should be different from earlier submissions

---

transformations/discourse_marker_substitution/README.md
transformations/discourse_marker_substitution/__init__.py
transformations/discourse_marker_substitution/test.json
transformations/discourse_marker_substitution/transformation.py

First commit fir discourse marker substitution transformer

Added discourse_marker_substitution

---

transformations/gender_culture_diverse_name/test.json
transformations/gender_culture_diverse_name/transformation.py
transformations/gender_culture_diverse_name_two_way/test.json
transformations/gender_culture_diverse_name_two_way/transformation.py

1. camel casing transformation name
2. added more test cases

update Gender culture diverse name transformation

---

.gitignore
dataset.py
evaluation/README.md
evaluation/evaluate_text_classification.py
evaluation/leaderboard_wrapper.py

Started a leaderboard for text classification. In the process, also changed the evaluation code for text classification so it's compatible to other models and tasks (qqp, nli, sst-2).

text classification leaderboard

---

transformations/geonames_transformation/README.md
transformations/geonames_transformation/__init__.py
transformations/geonames_transformation/countryInfo.txt
transformations/geonames_transformation/locales.txt
transformations/geonames_transformation/test.json
transformations/geonames_transformation/transformation.py

This is a data augmentation transformation making use of GeoNames. It will augment sentences containing cities or countries. More information in the README and examples are in test.json.

GeoNames data augmentation

---

README.md

Add link to informal ideas & discourage character level changes.

Add link to informal ideas

---

interfaces/README.md
interfaces/SentencePairOperation.py
tasks/TaskTypes.py
test/test_main.py
transformations/README.md
transformations/close_homophones_swap/transformation.py
transformations/gender_culture_diverse_name/transformation.py
transformations/gender_culture_diverse_name_two_way/transformation.py
transformations/lexical_counterfactual_generator/README.md
transformations/lexical_counterfactual_generator/__init__.py
transformations/lexical_counterfactual_generator/test.json
transformations/lexical_counterfactual_generator/transformation.py

Add interface and a sample transformation for sentence pair tasks (like paraphrase/entailment)

Sentence pair tasks interface

---

transformations/formality_change/README.md
transformations/formality_change/__init__.py
transformations/formality_change/test.json
transformations/formality_change/transformation.py

#77 combined casual2formal and formal2casual

Added formality change

---

test/test_main.py
transformations/gender_culture_diverse_name/test.json

[BUGFIX] (Correctly) Fail on Mismatched Numbers of Expected & Observed Examples

---

transformations/greetings_and_farewells/README.md
transformations/greetings_and_farewells/__init__.py
transformations/greetings_and_farewells/test.json
transformations/greetings_and_farewells/transformation.py

Hello everyone. Congratulations on this awesome project. I think it will be a big contribution to the community.
I created this transformation that **basically creates some text variants and perturbations on words and expressions related to greetings and farewells**. For instance, sentences containing words like "Hi!" or "What's up?" will have these words replaced by similar ones, like "Howdy" or "Good morning". The same behavior will be done for farewells and special cases (e.g. "It's nice to meet you" or "How's it going?").
**The main goal of this transformation is to tackle the robustness of text classification/generation models when faced with perturbations**.
Let me know if you need more details about the implementation.

Add "Greetings and Farewells" transformation

---

filters/toxicity/README.md
filters/toxicity/__init__.py
filters/toxicity/filter.py
filters/toxicity/requirements.txt
filters/toxicity/test.json
requirements.txt

Added a filter to select a subset of sentences based on toxicity.

Toxicity Filter

---

filters/repetitions/README.md
filters/repetitions/__init__.py
filters/repetitions/filter.py
filters/repetitions/test.json

This module filters examples which contain repetitions. This filter can be helpful to find text with repetitions that frequently occur in the spoken language data.
Author: Genta Indra Winata

Add Repetitions filter

---

evaluation/evaluate_text_classification.py

https://github.com/GEM-benchmark/NL-Augmenter/issues/172

Issue 172 on setting CUDA flag to true or false in evaluate function for users to be able to use CPU without issues

---

docs/doc.md
docs/keywords.md
evaluation/README.md
filters/keywords/filter.py
filters/question_filter/filter.py
filters/soundex/filter.py
interfaces/Operation.py
interfaces/README.md
test/keywords.py
test/test_main.py
transformations/add_hashtags/transformation.py
transformations/adjectives_antonyms_switch/transformation.py
transformations/back_translation/transformation.py
transformations/butter_fingers_perturbation/transformation.py
transformations/change_char_case/transformation.py
transformations/change_date_format/transformation.py
transformations/change_person_named_entities/transformation.py
transformations/change_two_way_ne/transformation.py
transformations/close_homophones_swap/transformation.py
transformations/contraction_expansions/transformation.py
transformations/gender_culture_diverse_name/transformation.py
transformations/propbank_srl_roles/transformation.py

Note that we would be sending a note shortly to everyone to include a list of keywords alongwith your transformations/filters.

All transformations should now add keywords

---

transformations/english_inflectional_variation/transformation.py

This adds the appropriate flags to the task which were previously set as object attributes

fix format of English inflection task.

---

evaluation/README.md
transformations/visual_attack_letters/README.md
transformations/visual_attack_letters/__init__.py
transformations/visual_attack_letters/test.json
transformations/visual_attack_letters/transformation.py

perturbs each character with a visually similar letter. Very relevant for profanity filters. Some future ideas: we could mix lowercase and uppercase letters. And also expand beyond the standard english alphabet.

Visual Attack Letters

---

transformations/pig_latin/transformation.py

Added keywords for the already-merged pig_latin transform (see https://github.com/GEM-benchmark/NL-Augmenter/pull/232#issuecomment-921216284).

Add keywords for Pig Latin transform 

---

transformations/neural_question_paraphraser/README.md
transformations/neural_question_paraphraser/__init__.py
transformations/neural_question_paraphraser/test.json
transformations/neural_question_paraphraser/transformation.py

Hello,
I have adresse the comments in https://github.com/GEM-benchmark/NL-Augmenter/pull/89.
Sorry for the late answer.
Cheers

added neural question parahraser follow up of https://github.com/GEM-benchmark/NL-Augmenter/pull/89

---

transformations/speech_disfluency_perturbation/README.md
transformations/speech_disfluency_perturbation/__init__.py
transformations/speech_disfluency_perturbation/test.json
transformations/speech_disfluency_perturbation/transformation.py

Simple perturbation to insert English filler words (e.g., "er", "uh", "um", etc...)

Implement speech disfluency perturbation

---

transformations/lost_in_translation/transformation.py
transformations/tag_subsequence_substitution/README.md
transformations/tag_subsequence_substitution/__init__.py
transformations/tag_subsequence_substitution/data.py
transformations/tag_subsequence_substitution/test.json
transformations/tag_subsequence_substitution/transformation.py

Add subsequence substitution for sequence tagging augmentation: https://aclanthology.org/2021.findings-acl.307.pdf

Added tag_subsequence_substitution

---

transformations/dyslexia_words_swap/README.md
transformations/dyslexia_words_swap/__init__.py
transformations/dyslexia_words_swap/data.json
transformations/dyslexia_words_swap/test.json
transformations/dyslexia_words_swap/transformation.py

Adding dyslexia_words_swap transformation.
This transformation acts like a perturbation by altering some words with mistakes that are likely to happen in the context of dyslexia.

feat: dyslexia_words_swap

---

.flake8
.github/workflows/nl-action.yml
.pre-commit-config.yaml
README.md
transformations/change_date_format/test.json

This PR addresses the following,
- Build failure fix because of change_date_format transformation
- Added badges in the README
- Added black profile in isort to prevent conflict

Build failure fix

---

transformations/yoda_transform/README.md
transformations/yoda_transform/__init__.py
transformations/yoda_transform/test.json
transformations/yoda_transform/transformation.py

This perturbation rearranges English sentences to read as if they were spoken by the Star Wars character Yoda. This introduces a linguistically interesting and rare variation in the input sentence data which can be used to test algorithm robustness. 
@jjangsangy @vinayprabhu @nick11roberts

Yoda transform

---

analysis/filters_mapping_analysis.py
analysis/mapping_analysis_utils.py
analysis/transformations_mapping_analysis.py

+ Refactored code so that mapping analysis can support both Transformations and Filters.
+ Added filters_mapping_analysis.py to generate CSVs for Filters metadata.

Filter Mapping Analysis

---

transformations/suspecting_paraphraser/transformation.py

fix: unnecessary print

---

setup.py

Updated the initial version and name.

Updated initial version and name of project

---

nlaugmenter/transformations/change_date_format/requirements.txt
requirements-light.txt

This PR will fix the github actions failure by fixing library versions of torchtext and dataparser.

Fixed requirements for change_date_format and torchtext

---

notebooks/Write_a_sample_transformation.ipynb

Hi.
Fixed errors in `Write_a_sample_transformation.ipynb` notebook:
- Lookup error: during imorting `omw-1.4` from nltk is needed
- ModuleNotFoundError: added prefix `nlaugmenter.` when importing from NL-Augmenter repo
Tested in google colab env: "Environment -> Run all" without errors.

Fixed errors in transformation notebook
